ROLE_CANDIDATE = "candidate"
ROLE_RECRUITER = "recruiter"
ROLE_HIRING_MANAGER = "hiring_manager"
ROLE_ADMIN = "admin"

SYSTEM_ROLES = (
  ROLE_CANDIDATE,
  ROLE_RECRUITER,
  ROLE_HIRING_MANAGER,
  ROLE_ADMIN,
)

RECRUITING_STAFF_ROLES = (
  ROLE_RECRUITER,
  ROLE_HIRING_MANAGER,
  ROLE_ADMIN,
)
